keys:
  - &cronos age133mrdqxr5ch5sjpwz80tkz79ewh8g5m248su3dd3z4wyntcq7v9sr6xqda
creation_rules:
  - path_regex: hosts/cronos/secrets.yaml$
    key_groups:
    - age:
      - *cronos
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
    - age:
      - *cronos
